---
- name: 01. Prepare all nodes (Common)
  hosts: k8s_cluster
  become: yes
  vars:
    pod_network_cidr: "192.168.0.0/16"
  roles:
    - common

- name: 02. Initialize Master Node
  hosts: masters
  become: yes
  roles:
    - master

- name: 03. Join Worker Nodes
  hosts: workers
  become: yes
  roles:
    - worker