
- name: Insuring .kube exists
  ansible.builtin.file:
    path: $HOME/.kube
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'

- name: Copying admin conf to user conf 
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Running calico.yaml 
  ansible.builtin.command:
    - kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/master/manifests/calico.yaml

- name: Generate join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set join command as a fact for all hosts
  ansible.builtin.set_fact:
    kubernetes_join_command: "{{ join_command_raw.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['all'] }}"

