# ---
# - name: Fetching SSH key for workers
#   host: master
#   become: yes
#   tasks:
#     - name: Key
#       ansible.builtin.command:
#         - kubeadm token create --print-join-command > $HOME/k8s_key.txt
