---
# Firewall for workers !
- name: Ensuring firewalld is running
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Adding Ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  loop:
    - 6443/tcp
    - 10250/tcp
    - 30000-32767/tcp
    - 4789/udp
    
- name: Reloading firewalld to apply permanent rules
  service:
    name: firewalld
    state: reloaded

# installinf networking packages 
- name: Installing mandatory networking packages
  apt:
    name: [conntrack, socat, ipset]
    state: present
    update_cache: yes

# setting up containerd and K8s
- name: Reseting containerd to K8s-compatible settings
  shell: |
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

- name: Applying containerd changes immediately
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes


# Joining key for connecting workers nodes to master
- name: Checking if node is already joined
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Joining worker to cluster
  command: >
    {{ hostvars[groups['masters'][0]].k8s_join_command }}
    --cri-socket unix:///var/run/containerd/containerd.sock
  when: not kubelet_conf.stat.exists